/*
export const DATA = [
	{
		id: '1',
		label: 'Food',
		children: [
			{
				id: '2',
				label: 'Meat',
			},
			{
				id: '3',
				label: 'Salad',
				children: [
					{
						id: '4',
						label: 'Tomatoes',
					},
					{
						id: '5',
						label: 'Cabbage',
					},
				],
			},
		],
	},
	{
		id: '6',
		label: 'Drinks',
		children: [
			{
				id: '7',
				label: 'Beer',
			},
			{
				id: '8',
				label: 'Soft drink',
			},
		],
	},
];
*/


export const DATA = [
	{
		id: '1',
		label: 'Home',
		link: '/',
	},
	{
		id: '2',
		label: 'About',
		link: '/about',
	},
	{
		id: '3',
		label: 'Nothing Here',
		link: '/nothing-here',
		desc: '',
	},
	{
		id: '4',
		label: 'Test',
		link: '/test',
		source: 'https://github.com/paulho1973/random-graph/tree/master/src/Test',
		desc: '',
	},
	{
		id: '5',
		label: 'Counter',
		link: '/counter',
		source: 'https://github.com/paulho1973/random-graph/tree/master/src/Counter',
		desc: ''
	},
	{
		id: '6',
		label: 'ApolloClient',
		link: '/apolloclient',
		source: 'https://github.com/paulho1973/random-graph/tree/master/src/ApolloTest',
		desc: '',
	},
	{
		id: '7',
		label: 'Iteration',
		link: '/iteration',
		source: 'https://github.com/paulho1973/random-graph/tree/master/src/Iteration',
		desc: '',
	},
	{
		id: '8',
		label: 'Center',
		link: '/center',
		desc: '',
	},
	{
		id: '9',
		label: 'Signup Form',
		link: '/signupform',
		source: 'https://github.com/paulho1973/random-graph/tree/master/src/SignupForm',
		desc: '',
	},
	{
		id: '10',
		label: 'Contact Form',
		link: '/contactform',
		source: 'https://github.com/paulho1973/random-graph/tree/master/src/ContactForm',
		desc: '',
	},
	{
		id: '11',
		label: 'Profile Form',
		link: '/profileform',
		source: 'https://github.com/paulho1973/random-graph/tree/master/src/ProfileForm',
		desc: '',
	},
	{
		id: '12',
		label: 'Button No',
		link: '/buttonno',
		source: 'https://github.com/paulho1973/random-graph/tree/master/src/ButtonNo',
		desc: '',
	},
	{
		id: '13',
		label: 'Page Layout 1',
		link: '/pagelayout1',
		source: 'https://github.com/paulho1973/random-graph/tree/master/src/PageLayout1',
		desc: '',
	},
	{
		id: '14',
		label: 'Page Layout 2',
		link: '/pagelayout2',
		source: 'https://github.com/paulho1973/random-graph/tree/master/src/PageLayout2',
		desc: '',
	},
	{
		id: '15',
		label: 'Page Layout 3',
		link: '/pagelayout3',
		source: 'https://github.com/paulho1973/random-graph/tree/master/src/PageLayout3',
		desc: '',
	},
	{
		id: '16',
		label: 'Page Layout 4',
		link: '/pagelayout4',
		source: 'https://github.com/paulho1973/random-graph/tree/master/src/PageLayout4',
		desc: '',
	},
	{
		id: '17',
		label: 'Section Scroll',
		link: '/sectionscroll',
		source: 'https://github.com/paulho1973/random-graph/tree/master/src/SectionScroll',
		desc: '',
	},
	{
		id: '18',
		label: 'React Ref',
		link: '/reactref',
		source: 'https://github.com/paulho1973/random-graph/tree/master/src/ReactRef',
		desc: '',
	},	
	{
		id: '19',
		label: 'Drag Drop Image',
		link: '/dragdropimage',
		source: 'https://github.com/paulho1973/random-graph/tree/master/src/DragDropImage',
		desc: '',
	},
	{
		id: '20',
		label: 'Drag Drop Display',
		link: '/dragdropdisplay',
		source: 'https://github.com/paulho1973/random-graph/tree/master/src/DragDropDisplay',
		desc: '',
	},
	{
		id: '21',
		label: 'Before Leave',
		link: '/beforeleave',
		source: 'https://github.com/paulho1973/random-graph/tree/master/src/BeforeLeave',
		desc: '',
	},
	{
		id: '22',
		label: 'Modal Demo',
		link: '/modaldemo',
		source: 'https://github.com/paulho1973/random-graph/tree/master/src/ModalDemo',
		desc: '',
	},
	{
		id: '23',
		label: 'Lazy Image',
		link: '/lazyimage',
		source: 'https://github.com/paulho1973/random-graph/tree/master/src/LazyImage',
		desc: '',
	},
	{
		id: '24',
		label: 'Search Bar',
		link: '/searchbar',
		source: 'https://github.com/paulho1973/random-graph/tree/master/src/SearchBar',
		desc: '',
	},
	{
		id: '25',
		label: 'Lazy Component',
		link: '/lazycomponent',
		source: 'https://github.com/paulho1973/random-graph/tree/master/src/LazyComponent',
		desc: '',
	},
	{
		id: '26',
		label: 'Toggle Switch',
		link: '/toggleswitch',
		source: 'https://github.com/paulho1973/random-graph/tree/master/src/ToggleSwitch',
		desc: '',
	},
	{
		id: '27',
		label: 'Dark Mode',
		link: '/darkmode',
		source: 'https://github.com/paulho1973/random-graph/tree/master/src/DarkMode',
		desc: '',
	},
	{
		id: '28',
		label: 'Modal Slide 1',
		link: '/modalslide1',
		source: 'https://github.com/paulho1973/random-graph/tree/master/src/ModalSlide1',
		desc: '',
	},
	{
		id: '29',
		label: 'Modal Slide 2',
		link: '/modalslide2',
		source: 'https://github.com/paulho1973/random-graph/tree/master/src/ModalSlide2',
		desc: '',
	},
	{
		id: '30',
		label: 'Modal Slide 3',
		link: '/modalslide3',
		source: 'https://github.com/paulho1973/random-graph/tree/master/src/ModalSlide3',
		desc: '',
	},
	{
		id: '31',
		label: 'Get Dimension',
		link: '/getdimension',
		source: 'https://github.com/paulho1973/random-graph/tree/master/src/GetDimension',
		desc: '',
	},
	{
		id: '32',
		label: 'Scroll Menu 1',
		link: '/scrollmenu1',
		source: 'https://github.com/paulho1973/random-graph/tree/master/src/ScrollMenu1',
		desc: '',
	},
	{
		id: '33',
		label: 'Swipe Menu 1',
		link: '/swipemenu1',
		source: 'https://github.com/paulho1973/random-graph/tree/master/src/SwipeMenu1',
		desc: '',
	},
];
